# Shows the "Sponsor" button at the top of the GitHub repo
custom:
  - "https://www.paypal.com/donate/?business=Moonmikejack%40hotmail.com&no_recurring=0&item_name=Support+XtremeLED+Remap+Export&currency_code=EUR"
